### ISSUE TITLE
Running issues

### ISSUE THREAD

**Issue by skodapetr** [VRK-YTI/yti-compose#1]
Recently I've tried to run docker-compose from this directory; however, I face several difficulties. Please find my experience describe bellow, I would also appreciate any help with the issues mentioned at the end.

For the whole process, I've been using the master branch.

# Build issues

In order to be able to build the project using ```bootstrap.sh``` and ```setup.sh``` with followup ```docker-compose``` I have to make several adjustments: 
- Add ```yti-messaging-api```, ```yti-activemq``` to ```./src/script/bootstrap.sh``` and ```./src/script/setup.sh``` project list.
- Add ```yti-postgres``` to ```./src/script/setup.sh```
- Update ```yti-spring-security:0.1.10``` to ```0.1.12``` for files:
   -  ```./src/script/build/yti-groupmanagement/web-api/build.gradle```
   -  ```./src/script/build/yti-codelist-content-intake-service/pom.xml```
   -  ```./src/script/build/yti-codelist-public-api-service/pom.xml```
   - ```./src/script/build/yti-comments-api/pom.xml```
   - ```./src/script/build/yti-terminology-api/build.gradle```
   - ```./src/script/build/yti-messaging-api/pom.xml```
- Update ```fi.vm.yti:yti-spring-migration:0.1.4``` to ```0.1.5-SNAPSHOT``` in
    - ```./src/script/build/yti-terminology-api/```
    - ```./src/script/build/yti-datamodel-api/build.gradle```
- Change ```gradle build``` to ```./gradlew build```
    - ```./src/script/build/yti-terminology-api/build.sh```
    - ```./src/script/build/yti-datamodel-api/build.sh ```

The versions need to be updated as the original version was not available (probably update in some repositories, not reflected others?) A solution might be to use a version range. 

With these modifications, the global Gradle is not required as it's using the provided wrapped version. On the other hand, an older version of Java (8) is required as the used Gradle version does not support Java 11. While this can be easily fixed, the Java 11 support would require additional code modifications as for example ```javax.annotation:javax.annotation-api:1.3.2``` needs to be added to ```yti-spring-migration```

# Docker-compose issues

Running ```docker-compose up``` cause:
```ERROR: for yti-datamodel-kibana  Cannot create container for service yti-datamodel-kibana: Conflict. The container name "/yti-kibana" is already in use by container "b9fd5f1f2cce8ee9b6e599499fb75c123e02dc9c9934e40a8f349f6f2c076d2d". You have to remove (or rename) that container to be able to reuse that name.``` There are in fact several services with the same name: ``` yti-kibana``` according to [docs](https://docs.docker.com/compose/compose-file/) ```Docker container names must be unique```. In order to work their names thus need to be changed.

When fix above issues and run ```docker-compose up``` I got multiple errors (causing restarts of containers) with:
```
 Caused by: java.net.UnknownHostException: yti-postgres
reason is 
yti-postgres | FATAL:  could not open log file "/data/logs/yti-postgres/postgresql-2020-01-07_153258.log": Permission denied
yti-postgres | LOG:  database system is shut down
yti-postgres exited with code 1
```
The issue with ```yti-postgres``` is that it tries to log into a host-mounted directory. However, the postgress process run with UID 999, but the directories are created as root. Thus user have to manually update their (not only for ```yti-postgres```) permission so they can use them.

Another minor issue with logging is that some logs are written into path that contains ```"{{projectname}}"```, by default this property is not resolved and directory ```/data/logs/"{{projectname}}"``` is created and used which is not ideal. A solution might be to use default values for properties.

# Final issues - blockers
After fixing all mentioned above I managed to run the docker-compose yet some containers still fail to start. IN the following list I put the name of the container and the exception.
- *yti-messaging-api*
```Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://yti-groupmanagement:8002/private-api/users": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)```
- *yti-codelist-content-intake-service*
```Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.```
- *yti-datamodel-api*
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'healthEndpoint' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthIndicatorRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthIndicatorAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthIndicatorRegistry]: Factory method 'healthIndicatorRegistry' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchRestHealthIndicatorAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticsearchRestClient' defined in class path resource [org/springframework/boot/autoconfigure/elasticsearch/rest/RestClientConfigurations$RestHighLevelClientConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.RestClient]: Factory method 'elasticsearchRestClient' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchClient' defined in class path resource [fi/vm/yti/datamodel/api/config/ElasticConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.RestHighLevelClient]: Factory method 'elasticSearchClient' threw exception; nested exception is java.lang.NumberFormatException: null
```
```
[yti-datamodel-api] Caused by: java.lang.NumberFormatException: null
[yti-datamodel-api]     at java.lang.Integer.parseInt(Integer.java:542)
[yti-datamodel-api]     at java.lang.Integer.parseInt(Integer.java:615)
[yti-datamodel-api]     at fi.vm.yti.datamodel.api.config.ElasticConfig.elasticSearchClient(ElasticConfig.java:35)
[yti-datamodel-api]     at fi.vm.yti.datamodel.api.config.ElasticConfig$$EnhancerBySpringCGLIB$$9519313c.CGLIB$elasticSearchClient$0(<generated>)
[yti-datamodel-api]     at fi.vm.yti.datamodel.api.config.ElasticConfig$$EnhancerBySpringCGLIB$$9519313c$$FastClassBySpringCGLIB$$5e1def1.invoke(<generated>)
[yti-datamodel-api]     at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
[yti-datamodel-api]     at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
[yti-datamodel-api]     at fi.vm.yti.datamodel.api.config.ElasticConfig$$EnhancerBySpringCGLIB$$9519313c.elasticSearchClient(<generated>)
[yti-datamodel-api]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[yti-datamodel-api]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[yti-datamodel-api]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[yti-datamodel-api]     at java.lang.reflect.Method.invoke(Method.java:498)
[yti-datamodel-api]     at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
[yti-datamodel-api]     ... 177 common frames omitted
```

It seems that the first and last issue may have something to do with configuration. But the middle issue may require a change of code. 

I would like to ask if this is the current state (maybe caused by using the latest version of repositories), whether the issues can be replicated and if so, whether there is a solution to them?

**Comment by amiika** [comment]
There were some conflicting ports and some issues related to the starting the whole system which are now fixed. Running "docker-compose up" should be working now but for the first time you should run "docker-compose up yti-groupmanagement-ui first and then init-admin.sh script to initialize one user and organization.
